#pragma once

// PEAS::Topology — the converter-topology taxonomy, as a SINGLE enum type.
//
// The taxonomy is PEAS-owned vocabulary: it is defined once in the PEAS schema
// (PEAS/schemas/utils.json#/$defs/topology — "PEAS HOSTS this shared vocabulary"). Its C++ enum is
// generated by quicktype into MAS.hpp as `MAS::Topology` (quicktype emits it in the MAS namespace
// because MAS::DesignRequirements references the $def, and quicktype has no cross-namespace type
// sharing). Rather than generate a SECOND, identical `PEAS::Topology` enum — which would be a distinct
// C++ type and invite silent switch/map mismatches — `PEAS::Topology` is an ALIAS of that one enum.
// There is exactly ONE `enum class` in the program; `MAS::Topology` and `PEAS::Topology` are the same
// type. Code refers to it as `PEAS::Topology` (PEAS owns the contract); the full definition + the
// to_json/from_json come from MAS.hpp, which any user of the enumerators already includes.

namespace MAS { enum class Topology : int; }   // forward-decl; full definition lives in the generated MAS.hpp

namespace PEAS {
// The one canonical taxonomy enum (= MAS::Topology, the single generated definition).
using Topology = ::MAS::Topology;
} // namespace PEAS
