#pragma once

// Kirchhoff::Topology — the canonical converter-topology taxonomy.
//
// Kirchhoff consumes the single generated `MAS::Topology` enum as its source of truth for "which
// converter" — instead of carrying ad-hoc topology strings. There is exactly ONE topology enum
// (`MAS::Topology`, generated by quicktype into MAS.hpp); Kirchhoff refers to it as `Kirchhoff::Topology`
// within its own namespace for brevity, but that is the SAME type — not a second enum.
//
// The taxonomy is PEAS-owned vocabulary at the SCHEMA layer (PEAS/schemas/utils.json#/$defs/topology,
// which MAS $refs), so `MAS::Topology`'s values + JSON serialization come from PEAS regardless of the
// C++ namespace quicktype emits them in. The enum's canonical JSON string is the exact camelCase the
// CTAS controller-seed `topology` field expects (Topology::FLYBACK_CONVERTER -> "flybackConverter").

#include "MAS.hpp"            // the single generated Topology enum definition (+ its to_json/from_json)
#include <nlohmann/json.hpp>
#include <string>

namespace Kirchhoff {

// The single Topology enum, named for brevity inside the Kirchhoff namespace.
using Topology = MAS::Topology;

// Serialize a topology to its canonical JSON string. THROWS via nlohmann if the enum value has no
// mapping — no silent fallback (per the no-fallbacks rule).
inline std::string topology_to_string(Topology t) {
    nlohmann::json j = t;            // MAS::to_json(json&, const Topology&)
    return j.get<std::string>();
}

} // namespace Kirchhoff
